import { env } from "./env";

export const databaseConfig = {
  connectionString: env.DATABASE_URL,
  schema: env.DATABASE_SCHEMA,
  max: 10,
  idleTimeoutMillis: 30_000,
  connectionTimeoutMillis: 5_000,
  application_name: env.APP_NAME
} as const;

export const databaseTables = {
  users: `${databaseConfig.schema}.users`,
  authRefreshTokens: `${databaseConfig.schema}.auth_refresh_tokens`,
  parents: `${databaseConfig.schema}.parents`,
  teachers: `${databaseConfig.schema}.teachers`,
  supervisors: `${databaseConfig.schema}.supervisors`,
  drivers: `${databaseConfig.schema}.drivers`,
  academicYears: `${databaseConfig.schema}.academic_years`,
  semesters: `${databaseConfig.schema}.semesters`,
  gradeLevels: `${databaseConfig.schema}.grade_levels`,
  classes: `${databaseConfig.schema}.classes`,
  subjects: `${databaseConfig.schema}.subjects`,
  teacherClasses: `${databaseConfig.schema}.teacher_classes`,
  supervisorClasses: `${databaseConfig.schema}.supervisor_classes`,
  students: `${databaseConfig.schema}.students`,
  studentParents: `${databaseConfig.schema}.student_parents`,
  studentPromotions: `${databaseConfig.schema}.student_promotions`,
  passwordResetTokens: `${databaseConfig.schema}.password_reset_tokens`,
  assessmentTypes: `${databaseConfig.schema}.assessment_types`,
  assessments: `${databaseConfig.schema}.assessments`,
  studentAssessments: `${databaseConfig.schema}.student_assessments`,
  homework: `${databaseConfig.schema}.homework`,
  homeworkSubmissions: `${databaseConfig.schema}.homework_submissions`,
  behaviorCategories: `${databaseConfig.schema}.behavior_categories`,
  behaviorRecords: `${databaseConfig.schema}.behavior_records`,
  attendanceSessions: `${databaseConfig.schema}.attendance_sessions`,
  attendance: `${databaseConfig.schema}.attendance`,
  buses: `${databaseConfig.schema}.buses`,
  routes: `${databaseConfig.schema}.routes`,
  busStops: `${databaseConfig.schema}.bus_stops`,
  studentBusAssignments: `${databaseConfig.schema}.student_bus_assignments`,
  trips: `${databaseConfig.schema}.trips`,
  busLocationHistory: `${databaseConfig.schema}.bus_location_history`,
  tripStudentEvents: `${databaseConfig.schema}.trip_student_events`,
  messages: `${databaseConfig.schema}.messages`,
  announcements: `${databaseConfig.schema}.announcements`,
  notifications: `${databaseConfig.schema}.notifications`
} as const;

export const databaseViews = {
  studentProfiles: `${databaseConfig.schema}.vw_student_profiles`,
  studentPrimaryParent: `${databaseConfig.schema}.vw_student_primary_parent`,
  classStudents: `${databaseConfig.schema}.vw_class_students`,
  attendanceDetails: `${databaseConfig.schema}.vw_attendance_details`,
  studentAttendanceSummary: `${databaseConfig.schema}.vw_student_attendance_summary`,
  classAttendanceSummary: `${databaseConfig.schema}.vw_class_attendance_summary`,
  assessmentDetails: `${databaseConfig.schema}.vw_assessment_details`,
  studentAssessmentDetails: `${databaseConfig.schema}.vw_student_assessment_details`,
  studentAssessmentSummary: `${databaseConfig.schema}.vw_student_assessment_summary`,
  homeworkDetails: `${databaseConfig.schema}.vw_homework_details`,
  homeworkSubmissionDetails: `${databaseConfig.schema}.vw_homework_submission_details`,
  behaviorDetails: `${databaseConfig.schema}.vw_behavior_details`,
  studentBehaviorSummary: `${databaseConfig.schema}.vw_student_behavior_summary`,
  routeStops: `${databaseConfig.schema}.vw_route_stops`,
  activeStudentBusAssignments: `${databaseConfig.schema}.vw_active_student_bus_assignments`,
  tripDetails: `${databaseConfig.schema}.vw_trip_details`,
  latestTripLocation: `${databaseConfig.schema}.vw_latest_trip_location`,
  activeTripLiveStatus: `${databaseConfig.schema}.vw_active_trip_live_status`,
  tripStudentEventDetails: `${databaseConfig.schema}.vw_trip_student_event_details`,
  vwMessageDetails: `${databaseConfig.schema}.vw_message_details`,
  vwUserInboxSummary: `${databaseConfig.schema}.vw_user_inbox_summary`,
  vwAnnouncementDetails: `${databaseConfig.schema}.vw_announcement_details`,
  vwActiveAnnouncements: `${databaseConfig.schema}.vw_active_announcements`,
  vwNotificationDetails: `${databaseConfig.schema}.vw_notification_details`,
  vwUserNotificationSummary: `${databaseConfig.schema}.vw_user_notification_summary`,
  adminDashboardSummary: `${databaseConfig.schema}.vw_admin_dashboard_summary`
} as const;
